# Generated by Django 5.0.7 on 2024-07-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0002_click_to_join_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crypto_Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.CharField(max_length=255)),
                ("text", models.CharField(max_length=1000000)),
                ("button_link", models.URLField()),
            ],
        ),
    ]
