# Generated by Django 5.0.7 on 2024-07-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0003_crypto_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="webinar",
            name="text",
        ),
        migrations.AddField(
            model_name="webinar",
            name="heading",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="webinar",
            name="text1",
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name="webinar",
            name="text2",
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
