# Generated by Django 5.0.7 on 2024-07-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0004_remove_webinar_text_webinar_heading_webinar_text1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motivation_section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=1000000)),
            ],
        ),
    ]
