# Generated by Django 5.0.7 on 2024-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0005_motivation_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="webinar",
            name="button_link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
