# Generated by Django 5.0.7 on 2024-07-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0006_webinar_button_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Click_To_Join_Link_Telegram_Channel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("button_link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Click_To_Join_Link_WhatsApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("button_link", models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Click_To_Join_Link",
            new_name="Click_To_Join_Link_Telegram",
        ),
        migrations.RemoveField(
            model_name="section_one",
            name="button_link",
        ),
    ]
