# Generated by Django 5.0.7 on 2024-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0007_click_to_join_link_telegram_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="click_to_join_link_telegram_channel",
            name="text1",
            field=models.CharField(max_length=10000000, null=True),
        ),
        migrations.AddField(
            model_name="click_to_join_link_telegram_channel",
            name="text2",
            field=models.CharField(max_length=10000000, null=True),
        ),
    ]
